# Generated by Django 3.1.7 on 2021-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german', models.CharField(max_length=64)),
                ('english', models.CharField(blank=True, max_length=64, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('article', models.CharField(blank=True, choices=[('der', 'der'), ('das', 'das'), ('die', 'die')], default='', max_length=4)),
                ('gender', models.CharField(blank=True, choices=[('m', 'masculine'), ('n', 'neuter'), ('f', 'feminine')], default='', max_length=16)),
                ('word_class', models.CharField(blank=True, choices=[('n', 'noun'), ('v', 'verb'), ('adv', 'adverb'), ('adj', 'adjective')], default='', max_length=16)),
            ],
        ),
    ]
