# Generated by Django 3.1.7 on 2021-03-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='words',
            field=models.ManyToManyField(related_name='groups', to='dictionary.Word'),
        ),
    ]
