# Generated by Django 3.1.7 on 2021-03-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20210327_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='dictionary.Word'),
        ),
    ]
