# Generated by Django 3.1.7 on 2021-03-28 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20210328_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
