# Generated by Django 3.1.7 on 2021-04-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_word_relevance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('-relevance',)},
        ),
    ]
