# Generated by Django 3.1.7 on 2021-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20210402_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='relevance',
            field=models.DecimalField(decimal_places=3, default=940.0, max_digits=7),
        ),
    ]
